framework:
    validation:
        enabled: true
        enable_attributes: true
        auto_mapping:
            App\Entity\: []

when@test:
    framework:
        validation:
            not_compromised_password: false
